[package]
name = "mavrik"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Biewer <biewers2@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
magnus = { version = "0.7", features = ["embed"] }
rutie = "0.9"
signal-hook = "0.3"
